---
title: "Stock_Analysis"
author: "Ryu"
date: '2020 3 31 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 라이브러리 활성화
```{r}
library(tidyverse)
library(lubridate)


```

# 데이터 로드
```{r}
krx_idx <- read.csv("KRX.csv", fileEncoding = "euc-kr") # 각 컬럼을 날짜형식으로 바꿔주자. 

str(krx_idx)
summary(krx_idx) 


krx_idx <- krx_idx %>% 
  filter(col())

# 첫번째 컬럼명 변경
names(krx_idx)[1] <- c("Index")

# 날짜 열값만 존재
krx_idx_only_date <- krx_idx[, -1]

# 

krx_idx[-1, ]

colnames(krx_idx) <- gsub("[.]", " ", colnames(krx_idx))
colnames(krx_idx) <- gsub("X", " ", colnames(krx_idx))
colnames(krx_idx) <- gsub("X", " ", colnames(krx_idx))





# krx_idx <- as.numeric(nrow(krx_idx))
# 
# krx_idx <- t(krx_idx)
# 
# split(krx_idx, krx_idx$X2006..01)
# 
# # tt <- t(krx_idx)
# aa <- krx_idx %>% 
#   group_by(krx_idx$Index = KRX 300) %>% 
#   summarise(cc = sum(krx_idx$Index = KRX 300))
# 
# krx_idx[, ] <- krx_idx[,ncol(krx_idx))]
# 
# col(krx_idx)
# row(krx_idx)
#  nchar(colnames(krx_idx))
#  length(krx_idx)
# 
# for (i in length()) {
#   
# }
#  
# rownames(krx_idx) <- colnames(krx_idx)
# 
# (nrow(krx_idx))


# colnames(krx_idx)
# aa <- colnames(krx_idx$지수종류별.1.)
# 
# krx_idx$지수종류별.1. <- aa
# 
# colnames(krx_idx$X2006..01) <- colnames("지수종류별")
# 실패
# colnames(krx_idx)[,1] <- "Index_name"
# 
# colnames(krx_idx)[,-1]
# 
# krx_idx[1,]

# # X와 . 추출
# deleting_index <- krx_idx %>% 
#   str_detect("X")
# 
# rm <- function(x) {
#   if(x = 9), {
#     subset()
#   }
#   a <- nchar(colnames(krx_idx)) 
#   
# }
# 
# nchar(colnames(krx_idx))
# 
# mode(colnames(krx_idx))
# 
# colnames(krx_idx) <- substring(colnames(krx_idx)2,8)
# 
# 
# colnames(krx_idx) <- gsub(".", "", colnames(krx_idx))


```

